source $HOME/.bash_shared


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/yoshihiro/.sdkman"
[[ -s "/home/yoshihiro/.sdkman/bin/sdkman-init.sh" ]] && source "/home/yoshihiro/.sdkman/bin/sdkman-init.sh"
