alias ls='ls -G'
alias l='ls'
alias ll='ls -la'
alias rm='rm -i'

PS1="\h:\w $ "

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if 
  command -v pyenv 1>/dev/null 2>&1; 
then
  eval "$(pyenv init -)"
fi


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

