set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
call vundle#end()
filetype plugin indent on

" settings

"文字コードをUFT-8に設定
set fenc=utf-8
" バックアップファイルを作らない
set nobackup
" スワップファイルを作らない
set noswapfile
" 編集中のファイルが変更されたら自動で読み直す
set autoread
" バッファが編集中でもその他のファイルを開けるように
set hidden
" 入力中のコマンドをステータスに表示する
set showcmd

 
" 行番号表示
set number

" ビープ音を可視化
set visualbell
" 括弧入力時の対応する括弧を表示
set showmatch

set background=dark

set virtualedit=onemore
set smartindent
set visualbell
set laststatus=2

set list listchars=tab:\▸\-
set expandtab
set tabstop=2
set shiftwidth=2

set incsearch
set wrapscan
set hlsearch
nmap <Esc><Esc> :nohlsearch<CR><Esc>

syntax on

set statusline+=%#warningmsg#

set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

autocmd vimenter * NERDTree

let g:go_version_warning = 0
